spring:
  data:
    mongodb:
      uri: mongodb://localhost/keyhole?replicaSet=replset&appName=mongo-spring-boot
logging:
  level:
    root: ERROR
    com.mongodb.client.model: INFO
    mongo.spring: DEBUG
    org.springframework.data.mongodb.core: DEBUG